site_name: Guild AI
docs_dir: pages
copyright: 2018-2019 TensorHub, Inc.
strict: true
extra:
  version: 0.6.0
  tagline_width: 20em
  tagline:

    The easiest way to run, track, and compare
    machine learning experiments

  subtext_width: 30em
  subtext:

  links:
    - name: github
      url: https://github.com/guildai/guildai
      title: Guild AI on GitHub
      icon_class: 'fab fa-github'
      header: yes
    - name: slack
      url: https://join.slack.com/t/guildai/shared_invite/enQtNDgxNDg5ODk2MjI2LWQ5ODI3ZGE2YzljYWViNTA0NjFmNDg4NTI3ZjY2Mjk2YTkzZjAxZWM3M2EyNTcyZWU0YzgzM2IwMTI0ZjFhNTU
      title: Guild AI Slack Channel
      icon_class: 'fab fa-slack-hash'
      header: yes
    - name: twitter
      url:  https://twitter.com/guildai
      title: Guild AI on Twitter
      icon_class: 'fab fa-twitter'

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true
  static_templates:
    - version.html
plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds
  - serve
markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - markdown_include.include:
      base_path: include
  - custom:DefinitionId
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:PkgConfigList:
      src_path: ./packages
  - custom:DeflistToTable
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure
  - custom:NonbreakingHyphens
  - custom:Link:
      templates:
        # external links
        - text_pattern: '(.+?)\s?->'
          text: '{}'
          class: ext
          target: _blank
        # command
        - link_pattern: 'cmd:(.*)'
          class: cmd
          href: '/docs/commands/{}-cmd'
          text: '{}'
        - link_pattern: 'pkg:(.*)'
          text: '{1}'
          href: /packages/{1}/
          class: pkg
        # term
        - link_pattern: 'term:(.*)'
          class: term
          text: '{0}'
          href: '{1}'
          arg_maps:
            - control-key: https://en.wikipedia.org/wiki/Control_key
              dependencies: /docs/dependencies.md
              flag: /docs/operations/#flags
              guild-env: /docs/environments/
              guild-file: /docs/reference/guild-file/
              guild-view: /docs/tools/guild-view/
              index: /docs/reference/guild-home/#runs-index
              model-def: /docs/models/#model-definition
              model: /docs/models/
              operation-alias: /docs/runs/#operation-aliases
              operation: /docs/operations/
              package-file: /docs/reference/package-file/
              package: /docs/packages/
              remote: /docs/remotes/
              resource-cache: /docs/reference/guild-home/#resource-cache
              resource: /docs/resources/
              run-dir: /docs/runs/#run-directory
              run: /docs/runs/
              tensorboard: /docs/tools/tensorboard/
              test: /docs/tests/
              user-config: /docs/reference/user-config/
        # aliases
        - link_pattern: alias:install-guild
          href: /install/
          text: install Guild AI
        - link_pattern: alias:quick-start
          href: /docs/start/
          text: Guild AI Quick Start
          class: doc
        - link_pattern: alias:guild-github
          href: https://github.com/guildai/guildai
          text: Guild AI GitHub project
          target: _blank
          class: ext
        - link_pattern: alias:guild-slack
          href: https://join.slack.com/t/guildai/shared_invite/enQtNDgxNDg5ODk2MjI2LWQ5ODI3ZGE2YzljYWViNTA0NjFmNDg4NTI3ZjY2Mjk2YTkzZjAxZWM3M2EyNTcyZWU0YzgzM2IwMTI0ZjFhNTU
          text: Guild AI Slack workspace
          class: ext
          target: _blank
        - link_pattern: alias:open-an-issue
          text: open an issue on GitHub
          class: ext
          target: _blank
          href: https://github.com/guildai/guildai/issues
        - link_pattern: alias:virtualenv-activate
          href: /docs/tutorials/workflow-with-virtualenv/#using-a-virtual-environment
          text: activate your virtual environment
        - link_pattern: alias:running-commands
          href: /docs/commands/#running-commands
          text: running commands
        - link_pattern: alias:separate-console
          href: /docs/commands/#running-commands-in-a-separate-console
          text: separate console
        - link_pattern: alias:tut-env-setup
          href: /docs/tutorials/#tutorial-virtual-environments
          text: Tutorial virtual environments
        - link_pattern: alias:tf-model-zoo
          href: https://github.com/tensorflow/models
          target: _blank
          class: ext
          text: TensorFlow model zoo
        - link_pattern: alias:packages
          href: /packages/
          text: Guild AI packages
        - link_pattern: alias:add-guild
          href: /docs/guides/add-guild/
          text: Add Guild to a project
        - link_pattern: alias:pip
          text: pip
          href: https://pip.pypa.io/en/stable/
          target: _blank
          class: ext
        - link_pattern: alias:tmux
          text: tmux
          href: https://en.wikipedia.org/wiki/Tmux
          target: _blank
          class: ext
        - link_pattern: alias:create-object-detector
          text: Create an object detector
          href: /docs/guides/create-object-detector/
        - link_pattern: alias:compare
          text: Guild Compare
          href: /docs/tools/compare/,

pages:
  - index.md
  - install.md
  - docs:
      - docs.md
      - Get Started:
          - start/index.md
          - start/optimization.md
      #- Concepts:
      - How To:
          - howto/run-script.md
          - howto/create-guild-file.md
          - howto/customize-operation-flags.md
          - howto/access-files-during-run.md
          - howto/tune-hyperparameters.md

      #- Reference:
  - quickref.md
  - support.md
