site_name: Guild AI
site_url: https://guild.ai
docs_dir: pages
copyright: 2018-2020 TensorHub, Inc.
strict: true
extra:
  version: 0.7.0
  contact_email: contact@guild.ai

  # IMPORTANT: keep the following in sync:
  #
  # - pages/index.md - title attr
  # - https://github.com/guildai/guildai - repo description
  #   (click cog in About section, upper right)
  # - short_site_description in my.guild.ai - under Settings, Required
  tagline:

    Open Source Experiment Tracking for Machine Learning

  tagline_width: 18em

  other_taglines:
    - The ML Engineering Platform
    - The ML Engineering Toolkit
    - Open source tools for ML engineering
    - Experiment Tracking for Machine Learning
    - Open Source Experiment Tracking for Machine Learning
    - Open Source ML Experiment Tracking

  subtext_width: 40em
  subtext:

  tagline_bullets:
    - text: Compare & Analyze
      icon: analytics-graph-white
    - text: Automate Pipelines
      icon: hierarchy-white
    - text: Optimize Models
      icon: seo-search-graph-gray
    - text: Platform Independent
      icon: programming-flag-gray

  navbar:
    - name: Why Guild
      url: /why-guild/
    - name: Docs
      url: https://my.guild.ai/docs
    - name: FAQ
      url: /faq/
    - name: Services
      url: /services/

  links:
    - name: github
      url: https://github.com/guildai/guildai
      title: Guild AI on GitHub
      icon_class: 'fab fa-github'
      header: yes
    - name: my.guild.ai
      url: https://my.guild.ai
      title: Guild AI Community
      icon_class: 'fab fa-discourse'
      header: yes
    - name: twitter
      url:  https://twitter.com/guildai
      title: Guild AI on Twitter
      icon_class: 'fab fa-twitter'
      header: yes

  # URL to edit Google fonts used in src/base.html:
  #
  # https://fonts.google.com/specimen/Roboto+Condensed?selection.family=Roboto+Condensed:wght@400;700|Roboto+Mono|Roboto+Slab|Roboto:wght@400;500;700&sidebar.open&query=roboto

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true

plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds:
  - serve

markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - extra
  - markdown_include.include:
      base_path: include
  - custom:MarkdownInHtml
  - custom:DefinitionId
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:PkgConfigList:
      src_path: ./packages
  - custom:DeflistToTable
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure

pages:
  - index.md
  - why-guild.md
  - services.md
  - faq.md
  - about.md
