site_name: Guild AI
docs_dir: pages

copyright: 2017-2018 TensorHub, Inc.
extra:
  tagline: Standardize your deep learning workflow
  subtext:
    Train, evaluate, and deploy your TensorFlow<sup>&trade;</sup> and
    Keras in less time and with fewer errors with the Guild AI
    developer toolkit.
  subtext_width: 32em
  links:
    - name: github
      url: https://github.com/guildai
    - name: twitter
      url:  https://twitter.com/guild_ai

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true
  static_templates:
    - search.html

plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds
  - serve

markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - custom:DefinitionId
  - custom:DeflistToTable
  - custom:CmdHelp:
      src_path: ../guild/guild/commands/
  - custom:PkgHelp:
      src_path: ../guild-packages
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure
  - custom:Link:
      templates:
        # external links
        - text_pattern: '(.+?)\s?->'
          text: '{}'
          class: ext
          target: _blank
        # command
        - link_pattern: 'cmd:(.*)'
          class: cmd
          href: '/docs/commands/{}-cmd'
          text: '{}'
        # term
        - link_pattern: 'term:(.*)'
          class: term
          text: '{0}'
          href: '{1}'
          arg_maps:
            - control-key: https://en.wikipedia.org/wiki/Control_key
              flag: /docs/operations/#flags
              index: /docs/reference/guild-home/#runs-index
              model: /docs/models/
              model-def: /docs/models/#model-definition
              operation: /docs/operations/
              operation-alias: /docs/runs/#operation-aliases
              package-file: /docs/reference/package-file/
              package: /docs/packages/
              resource: /docs/resources/
              resource-cache: /docs/reference/guild-home/#resource-cache
              run-dir: /docs/runs/#run-directory
              run: /docs/runs/
        # aliases
        - link_pattern: alias:guild-github
          class: ext
          target: _blank
          href: https://github.com/guildai/guild
          text: Guild AI GitHub project
        - link_pattern: alias:open-an-issue
          text: open an issue on GitHub
          class: ext
          target: _blank
          href: https://github.com/guildai/guild/issues
        - link_pattern: alias:virtualenv-activate
          href: /docs/tutorials/workflow-with-virtualenv/#using-a-virtual-environment
          text: activate your virtual environment
        - link_pattern: alias:running-commands
          href: /docs/commands/#running-commands
          text: running commands
        - link_pattern: alias:separate-console
          href: /docs/commands/#running-commands-in-a-separate-console
          text: separate console
        - link_pattern: alias:tut-env-setup
          href: /docs/tutorials/#tutorial-virtual-environments
          text: Tutorial virtual environments
        - link_pattern: alias:tf-model-zoo
          href: https://github.com/tensorflow/models
          target: _blank
          class: ext
          text: TensorFlow model zoo

pages:
  - index.md
  - install.md
  - docs:
      - docs/index.md
      - docs/overview.md
      - docs/models.md
      - docs/operations.md
      - docs/runs.md
      - Visualization:
          - docs/visual/index.md
          - docs/visual/guild-view.md
          - docs/visual/tensorboard.md
      - docs/packages.md
      - docs/resources.md
      - Commands:
          - docs/commands/index.md
          - docs/commands/check-cmd.md
          - docs/commands/compare-cmd.md
          - docs/commands/help-cmd.md
          - docs/commands/index-cmd.md
          - docs/commands/install-cmd.md
          - docs/commands/models-cmd.md
          - docs/commands/operations-cmd.md
          - docs/commands/package-cmd.md
          - docs/commands/packages-cmd.md
          - docs/commands/packages-delete-cmd.md
          - docs/commands/packages-info-cmd.md
          - docs/commands/packages-list-cmd.md
          - docs/commands/resources-cmd.md
          - docs/commands/run-cmd.md
          - docs/commands/runs-cmd.md
          - docs/commands/runs-delete-cmd.md
          - docs/commands/runs-info-cmd.md
          - docs/commands/runs-label-cmd.md
          - docs/commands/runs-list-cmd.md
          - docs/commands/runs-purge-cmd.md
          - docs/commands/runs-restore-cmd.md
          - docs/commands/search-cmd.md
          - docs/commands/shell-cmd.md
          - docs/commands/sync-cmd.md
          - docs/commands/tensorboard-cmd.md
          - docs/commands/tensorflow-cmd.md
          - docs/commands/tensorflow-inspect-checkpoint-cmd.md
          - docs/commands/train-cmd.md
          - docs/commands/uninstall-cmd.md
          - docs/commands/view-cmd.md
      - Plugins:
          - docs/plugins/index.md
          - docs/plugins/cloudml.md
          - docs/plugins/cpu.md
          - docs/plugins/disk.md
          - docs/plugins/keras.md
          - docs/plugins/gpu.md
          - docs/plugins/memory.md
      - Developer guides:
          - docs/developer/scripts.md
          - docs/developer/packaging.md
          - docs/developer/plugins.md
      - Reference:
          - docs/reference/plugin-api.md
          - docs/reference/model-file.md
          - docs/reference/package-file.md
          - docs/reference/guild-home.md
      - Tutorials:
          - docs/tutorials/index.md
          - docs/tutorials/train-mnist.md
          - docs/tutorials/transfer-learning-with-imagenet.md
          - docs/tutorials/train-and-predict-with-cloudml.md
          - docs/tutorials/train-a-keras-model.md
          - docs/tutorials/develop-a-model-from-scratch.md
          - docs/tutorials/package-a-model.md
          - docs/tutorials/stylize-images-with-magenta.md
          - docs/tutorials/create-a-custom-dataset.md
          - docs/tutorials/workflow-with-virtualenv.md
      - troubleshooting.md
  - models:
      - models/index.md
      - Keras:
          - models/keras/index.md
          - models/keras/mnist.md
      - models/magenta.md
      - models/tensorflow.md
      - TF Slim:
          - models/slim/index.md
          - models/slim/resnet.md
  - support.md
  - faq.md
  - about.md
