site_name: Guild AI
docs_dir: pages

copyright: 2017-2018 TensorHub, Inc.
extra:
  links:
    - name: github
      url: https://github.com/guildai
    - name: twitter
      url:  https://twitter.com/guild_ai

theme:
  name: null
  custom_dir: src

plugins:
  - search
  - nav_resolve

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - smarty
  - toc
  - custom:FixToc
  - custom:DefinitionId
  - custom:ExternalLink
  - custom:TagList
  - custom:LinkAlias:
      term:
        href: '/docs/glossary/#{}'
        text: '{}'
        class: 'term'
      open-an-issue:
        href: 'https://github.com/guildai/guild/issues'
        text: 'open an issue on GitHub->'
      virtualenv-activate:
        href: 'https://virtualenv.pypa.io/en/stable/userguide/#activate-script'
        text: 'Virtualenv->'
      cmd:
        href: '/docs/commands/{}_cmd'
        text: '{}'
        class: 'cmd'

pages:
  - index.md
  - install.md
  - docs:
      - docs/index.md
      - docs/overview.md
      - docs/packages.md
      - docs/models.md
      - docs/operations.md
      - docs/runs.md
      - Visualization:
          - docs/visual/index.md
          - docs/visual/guild-view.md
          - docs/visual/tensorboard.md
      - Commands:
          - docs/commands/index.md
          - docs/commands/check_cmd.md
          - docs/commands/compare_cmd.md
          - docs/commands/help_cmd.md
          - docs/commands/index_cmd.md
          - docs/commands/install_cmd.md
          - docs/commands/models_cmd.md
          - docs/commands/operations_cmd.md
          - docs/commands/package_cmd.md
          - docs/commands/packages_cmd.md
          - docs/commands/resources_cmd.md
          - docs/commands/run_cmd.md
          - docs/commands/runs_cmd.md
          - docs/commands/search_cmd.md
          - docs/commands/shell_cmd.md
          - docs/commands/sync_cmd.md
          - docs/commands/tensorboard_cmd.md
          - docs/commands/tensorflow_cmd.md
          - docs/commands/train_cmd.md
          - docs/commands/uninstall_cmd.md
          - docs/commands/view_cmd.md
      - Plugins:
          - docs/plugins/index.md
          - docs/plugins/cloudml.md
          - docs/plugins/cpu.md
          - docs/plugins/disk.md
          - docs/plugins/keras.md
          - docs/plugins/gpu.md
          - docs/plugins/memory.md
      - Developer guides:
          - docs/developer/packaging.md
          - docs/developer/plugins.md
      - Reference:
          - docs/reference/plugin-api.md
          - docs/reference/model-file.md
          - docs/reference/package-file.md
      - Tutorials:
          - docs/tutorials/index.md
          - docs/tutorials/train-your-first-model.md
          - docs/tutorials/transfer-learning-with-imagenet.md
          - docs/tutorials/guild-from-scratch.md
          - docs/tutorials/working-with-virtualenv.md
      - docs/glossary.md
  - models:
      - models/index.md
      - models/keras.md
      - models/magenta.md
      - models/tensorflow.md
      - models/tfslim.md
  - support.md
  - about.md
