site_name: Guild AI
docs_dir: pages
copyright: 2018-2019 TensorHub, Inc.
strict: true
extra:
  version: 0.6.6

  tagline_width: 30em

  # NOTE: Update title in pages/index.md to sync with tagline.
  #
  tagline:

    The ML Engineering Platform

  subtext_width: 40em
  subtext:

  tagline_bullets:
    - text: Experiment Tracking
      icon: folder-check-gray

    - text: Auto ML
      icon: seo-search-graph-gray

    - text: Pipeline Automation
      icon: hierarchy-10-gray

    - text: Vendor Independent
      icon: cloud-star-gray

  links:
    - name: github
      url: https://github.com/guildai/guildai
      title: Guild AI on GitHub
      icon_class: 'fab fa-github'
      header: yes
    - name: slack
      url: https://join.slack.com/t/guildai/shared_invite/enQtNDgxNDg5ODk2MjI2LWQ5ODI3ZGE2YzljYWViNTA0NjFmNDg4NTI3ZjY2Mjk2YTkzZjAxZWM3M2EyNTcyZWU0YzgzM2IwMTI0ZjFhNTU
      title: Guild AI Slack Channel
      icon_class: 'fab fa-slack-hash'
      header: yes
    - name: twitter
      url:  https://twitter.com/guildai
      title: Guild AI on Twitter
      icon_class: 'fab fa-twitter'

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true

plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds
  - serve

markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - extra
  - markdown_include.include:
      base_path: include
  - custom:MarkdownInHtml
  - custom:DefinitionId
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:PkgConfigList:
      src_path: ./packages
  - custom:DeflistToTable
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure
  - custom:NonbreakingHyphens
  - custom:Link:
      templates:

        # external link
        - text_pattern: '(.+?)\s?->'
          text: '{}'
          class: ext
          target: _blank

        # external link alt (supports formatting)
        - link_pattern: 'ext:(.*)'
          class: ext
          href: '{}'
          target: _blank

        # command
        - link_pattern: 'cmd:(.*)'
          class: cmd
          href: '/commands/{}/'
          text: '{}'

        # Python lib
        - link_pattern: 'pylib:(.*)'
          class: ext pkg
          href: 'https://docs.python.org/3/library/{}.html'
          text: '{}'
          target: _blank

        # Guild package
        - link_pattern: 'pkg:(.*)'
          text: '{1}'
          href: /packages/{1}/
          class: pkg

        - link_pattern: ref:conda
          text: Conda
          class: ext
          target: _blank
          href: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/environments.html

        - link_pattern: ref:meld
          text: Meld
          class: ext
          target: _blank
          href: https://meldmerge.org/

        - link_pattern: ref:open-an-issue
          text: open an issue on GitHub
          class: ext
          target: _blank
          href: https://github.com/guildai/guildai/issues

        - link_pattern: ref:pip-reqs
          text: pip requirement specification
          class: ext
          target: _blank
          href: https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers

        - link_pattern: ref:slack
          href: https://join.slack.com/t/guildai/shared_invite/enQtNDgxNDg5ODk2MjI2LWQ5ODI3ZGE2YzljYWViNTA0NjFmNDg4NTI3ZjY2Mjk2YTkzZjAxZWM3M2EyNTcyZWU0YzgzM2IwMTI0ZjFhNTU
          text: Guild AI Slack workspace
          class: ext
          target: _blank

        - link_pattern: ref:terraform
          href: https://www.terraform.io/
          text: Terraform
          class: ext
          target: _blank

        - link_pattern: ref:virtualenv
          href: https://virtualenv.pypa.io/en/latest/
          text: virtualenv
          class: ext
          target: _blank

        # ref (general)
        - link_pattern: '(ref|term):(.*)'
          text: '{0}'
          href: '{3}'
          class: '{2}'
          arg_maps:
            - {}
            -
              autodetect-flags: /kb/autodetect-flags.md
              bayesian-optimization: https://en.wikipedia.org/wiki/Bayesian_optimization
              flag: /guildfile.md#flags
              flags: /guildfile.md#flags
              full-format: /reference/guildfile.md#full-format
              grid-search: https://en.wikipedia.org/wiki/Hyperparameter_optimization#Grid_search
              guild-compare: /tools.md#guild-compare
              guildfile: /guildfile.md
              guildfiles: /guildfile.md
              guild-view: /tools.md#guild-view
              main-mod: https://docs.python.org/3/using/cmdline.html#cmdoption-m
              no-databases: /faq/#how-does-guild-save-results
              operation-only-format: /reference/guildfile.md#operation-only-format
              operation: /guildfile.md#operations
              operations: /guildfile.md#operations
              output-scalar: /guildfile.md#output-scalars
              output-scalars: /guildfile.md#output-scalars
              random-search: https://en.wikipedia.org/wiki/Random_search
              remotes: /reference/remotes.md
              requirements: /guildfile.md#required-resources
              run: /runs.md
              run-dir: /runs.md#run-directory
              ssh: https://en.wikipedia.org/wiki/Secure_Shell
              step: /reference/guildfile.md#steps
              steps: /reference/guildfile.md#steps
              source-code: /guildfile.md#source-code
              user-config: /reference/user-config.md

pages:
  - index.md
  - docs:
      - docs.md
      - install.md

      - Get Started:
          - start.md
          - start/optimize.md
          - start/runs.md
          - start/guildfile.md
          - start/classifier.md
          - start/workflow.md
          - start/explore.md

      - Concepts:
          - architecture.md
          - cli.md
          - guildfile.md
          - runs.md
          - tools.md
          - workflow.md
          - remote.md
          - backup-and-restore.md
          ##- publishing.md
          - environments.md

      - Guides:
          - guides/add.md
          - guides/compare.md
          ##- guides/workflow.md
          - guides/reproducibility.md
          ##- guides/schedule.md
          ##- guides/remote.md
          ##- guides/backup.md
          - guides/notebooks.md
          - guides/troubleshoot.md

      - Commands:
          - commands/index.md
          - commands/cat.md
          - commands/check.md
          - commands/compare.md
          - commands/diff.md
          - commands/download.md
          - commands/export.md
          - commands/help.md
          - commands/import.md
          - commands/init.md
          - commands/install.md
          - commands/label.md
          - commands/ls.md
          - commands/models.md
          - commands/open.md
          - commands/operations.md
          - commands/package.md
          - commands/packages-delete.md
          - commands/packages-info.md
          - commands/packages-list.md
          - commands/packages.md
          - commands/pull.md
          - commands/push.md
          - commands/remote-start.md
          - commands/remote-status.md
          - commands/remote-stop.md
          - commands/remote.md
          - commands/remotes.md
          - commands/run.md
          - commands/runs-delete.md
          - commands/runs-diff.md
          - commands/runs-export.md
          - commands/runs-import.md
          - commands/runs-info.md
          - commands/runs-label.md
          - commands/runs-list.md
          - commands/runs-pull.md
          - commands/runs-purge.md
          - commands/runs-push.md
          - commands/runs-restore.md
          - commands/runs-stop.md
          - commands/runs.md
          - commands/search.md
          - commands/shell.md
          - commands/stop.md
          - commands/sync.md
          - commands/tensorboard.md
          - commands/tensorflow-inspect.md
          - commands/tensorflow.md
          - commands/uninstall.md
          - commands/view.md
          - commands/watch.md

      - Reference:
          - reference/guildfile.md
          - reference/user-config.md
          - reference/remotes.md

      - Knowledge Base:
          - kb/dependencies.md
          - kb/autodetect-flags.md
          - kb/model-reuse.md
          - kb/git-for-tracking.md

      - Cheatsheets:
          - cheatsheets/commands.md
          - cheatsheets/guildfile.md
          - cheatsheets/remotes.md

  #- examples.md
  - faq.md
  - services.md
