site_name: Guild AI
docs_dir: pages
copyright: 2018-2020 TensorHub, Inc.
strict: true
extra:
  version: 0.7.0
  contact_email: contact@guild.ai

  tagline_width: 30em

  tagline:  # IMPORTANT: sync pages/index.md title with tagline

    The ML Engineering Platform

  subtext_width: 40em
  subtext:

  tagline_bullets:
    - text: Experiment Tracking
      icon: folder-check-gray

    - text: Pipeline Automation
      icon: hierarchy-10-gray

    - text: Auto ML
      icon: seo-search-graph-gray

    - text: 100% Open Source
      icon: programming-flag-gray

  links:
    - name: github
      url: https://github.com/guildai/guildai
      title: Guild AI on GitHub
      icon_class: 'fab fa-github'
      header: yes
    - name: slack
      url: https://join.slack.com/t/guildai/shared_invite/enQtNDgxNDg5ODk2MjI2LWQ5ODI3ZGE2YzljYWViNTA0NjFmNDg4NTI3ZjY2Mjk2YTkzZjAxZWM3M2EyNTcyZWU0YzgzM2IwMTI0ZjFhNTU
      title: Guild AI on Slack
      icon_class: 'fab fa-slack-hash'
      header: yes
    - name: twitter
      url:  https://twitter.com/guildai
      title: Guild AI on Twitter
      icon_class: 'fab fa-twitter'

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true

plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds
  - serve

markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - extra
  - markdown_include.include:
      base_path: include
  - custom:MarkdownInHtml
  - custom:DefinitionId
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:PkgConfigList:
      src_path: ./packages
  - custom:DeflistToTable
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure
  - custom:NonbreakingHyphens
  - custom:Link:
      templates:

        # external link
        - text_pattern: '(.+?)\s?-(?:>|&gt;)'
          text: '{}'
          class: ext
          target: _blank

        # external link alt (supports formatting)
        - link_pattern: 'ext:(.*)'
          class: ext
          href: '{}'
          target: _blank

        # command
        - link_pattern: 'cmd:(.*)'
          class: cmd
          href: '/commands/{}/'
          text: '{}'

        # Python lib
        - link_pattern: 'pylib:(.*)'
          class: ext pkg
          href: 'https://docs.python.org/3/library/{}.html'
          text: '{}'
          target: _blank

        # Guild package
        - link_pattern: 'pkg:(.*)'
          text: '{1}'
          href: /packages/{1}/
          class: pkg

        # specific references

        - link_pattern: ref:get-help
          text: ask for help
          href: /services.md#support

        - link_pattern: ref:conda
          text: Conda
          class: ext
          target: _blank
          href: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/environments.html

        - link_patern: ref:guild-examples
          text: Guild examples
          class: ext
          taget: _blank
          href: https://github.com/guildai/examples

        - link_pattern: ref:hiplot
          text: HiPlot
          class: ext
          target: _blank
          href: https://facebookresearch.github.io/hiplot/index.html

        - link_pattern: ref:meld
          text: Meld
          class: ext
          target: _blank
          href: https://meldmerge.org/

        - link_pattern: ref:open-an-issue
          text: open an issue on GitHub
          class: ext
          target: _blank
          href: https://github.com/guildai/guildai/issues

        - link_pattern: ref:pip-reqs
          text: pip requirement specification
          class: ext
          target: _blank
          href: https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers

        - link_pattern: ref:slack
          href: https://join.slack.com/t/guildai/shared_invite/enQtNDgxNDg5ODk2MjI2LWQ5ODI3ZGE2YzljYWViNTA0NjFmNDg4NTI3ZjY2Mjk2YTkzZjAxZWM3M2EyNTcyZWU0YzgzM2IwMTI0ZjFhNTU
          text: Guild AI Slack workspace
          class: ext
          target: _blank

        - link_pattern: (ref|term):regex
          href: https://docs.python.org/library/re.html#regular-expression-syntax
          text: regular expression
          class: ext {1}
          target: _blank

        - link_pattern: ref:tensorboard
          href: https://www.tensorflow.org/tensorboard
          text: TensorBoard
          class: ext
          target: _blank

        - link_pattern: ref:terraform
          href: https://www.terraform.io/
          text: Terraform
          class: ext
          target: _blank

        - link_pattern: ref:virtualenv
          href: https://virtualenv.pypa.io/en/latest/
          text: virtualenv
          class: ext
          target: _blank

        # ref (general)
        - link_pattern: '(ref|term):(.*)'
          text: '{0}'
          href: '{3}'
          class: '{2}'
          arg_maps:
            - {}
            -
              autodetect-flags: /kb/autodetect-flags.md
              batch: /runs.md#batches
              batch-file: /runs.md#batch-files
              bayesian-optimization: https://en.wikipedia.org/wiki/Bayesian_optimization
              cli: /cli.md
              dependency: /dependencies.md
              environment: /environments.md
              flag-search-space-function: /flags.md#search-space-functions
              flag-sequence-function: /flags.md#sequence-functions
              flag-value-list: /flags.md#value-lists
              flag: /flags.md
              flags: /flags.md
              flags-import: /flags.md#flag-imports
              flags-interface: /flags.md#flags-interface
              full-format: /reference/guildfile.md#full-format
              grid-search: https://en.wikipedia.org/wiki/Hyperparameter_optimization#Grid_search
              guild-compare: /tools/compare.md
              guild-diff: /tools/diff.md
              guild-home: /environments/#set-guild-home
              guild-tensorboard: /tools/tensorboard.md
              guild-view: /tools/view.md
              guildfile: /guildfile.md
              guildfiles: /guildfile.md
              main-mod: https://docs.python.org/3/using/cmdline.html#cmdoption-m
              model: /guildfile.md#models
              no-databases: /faq/#how-does-guild-save-results
              operation-only-format: /reference/guildfile.md#operation-only-format
              operation: /operations.md
              operations: /operations.md
              output-scalar: /scalars.md#output-scalars
              output-scalars: /scalars.md#output-scalars
              random-search: https://en.wikipedia.org/wiki/Random_search
              remotes: /reference/remotes.md
              requirements: /guildfile.md#required-resources
              run-dir: /runs.md#run-directory
              run: /runs.md
              scalar: /scalars.md
              source-code: /guildfile.md#source-code
              ssh: https://en.wikipedia.org/wiki/Secure_Shell
              step: /workflow.md#steps
              steps: /workflow.md#steps
              summaries: /tools/tensorboard.md#summaries
              user-config: /reference/user-config.md
              workflow: /workflow.md

pages:
  - index.md
  - docs:
      - docs.md
      - install.md

      - Get Started:
          - start/index.md
          - start/optimize.md
          - start/runs.md
          - start/guildfile.md
          - start/classifier.md
          - start/nextsteps.md

      - Concepts:
          - cli.md
          - runs.md
          - guildfile.md
          - operations.md
          - flags.md
          - scalars.md
          - dependencies.md
          - workflow.md
          - queues.md
          - environments.md
          - remotes.md
          - notebooks.md
          #- publishing.md

      - Tools:
          - tools/compare.md
          - tools/view.md
          - tools/tensorboard.md
          - tools/diff.md

      - Guides:
          - guides/workflow.md
          #- guides/add-guild.md
          #- guides/dependencies.md
          - guides/backup-restore.md
          - guides/upgrade.md
          - guides/tips-and-techniques.md
          #- guides/reproducibility.md

      - Commands:
          - commands/index.md
          - commands/cat.md
          - commands/check.md
          - commands/compare.md
          - commands/diff.md
          - commands/download.md
          - commands/export.md
          - commands/help.md
          - commands/import.md
          - commands/init.md
          - commands/install.md
          - commands/label.md
          - commands/ls.md
          - commands/models.md
          - commands/open.md
          - commands/operations.md
          - commands/ops.md
          - commands/package.md
          - commands/packages.md
          - commands/packages-delete.md
          - commands/packages-info.md
          - commands/packages-list.md
          - commands/pull.md
          - commands/push.md
          - commands/remote.md
          - commands/remote-start.md
          - commands/remote-status.md
          - commands/remote-stop.md
          - commands/remotes.md
          - commands/run.md
          - commands/runs.md
          - commands/runs-delete.md
          - commands/runs-diff.md
          - commands/runs-export.md
          - commands/runs-import.md
          - commands/runs-info.md
          - commands/runs-label.md
          - commands/runs-list.md
          - commands/runs-pull.md
          - commands/runs-purge.md
          - commands/runs-push.md
          - commands/runs-restore.md
          - commands/runs-rm.md
          - commands/runs-stop.md
          - commands/search.md
          - commands/select.md
          - commands/shell.md
          - commands/stop.md
          - commands/sync.md
          - commands/tensorboard.md
          - commands/tensorflow.md
          - commands/tensorflow-inspect.md
          - commands/uninstall.md
          - commands/view.md
          - commands/watch.md

      - Reference:
          - reference/guildfile.md
          - reference/optimizers.md
          - reference/remotes.md
          - reference/user-config.md
          - reference/plugins.md
          - reference/defaults.md
          - reference/design.md

      #- Knowledge Base:
      #    - kb/configure-flags.md
      #    - kb/guild-vs-others.md
      #    #- kb/dependencies.md
      #    #- kb/autodetect-flags.md
      #    #- kb/model-reuse.md

      - Cheatsheets:
          - cheatsheets/commands.md
          - cheatsheets/guildfile.md
          - cheatsheets/remotes.md

  - faq.md
  - services.md
  - about.md
