site_name: Guild AI
site_url: https://guild.ai
docs_dir: pages
copyright: 2018-2020 TensorHub, Inc.
strict: true
extra:
  version: 0.7.0
  contact_email: contact@guild.ai

  # Used for page titles. Important for SEO. Mirror this in these
  # locations:
  #
  # - https://github.com/guildai/guildai - repo description (from
  #   link, click cog in About section, upper right)
  #
  # - short_site_description in my.guild.ai - under Settings, Required
  #
  # - PyPI description - specified in Guild source in
  # - guildai.dist-info/METADATA as Summary
  #
  title_base: Experiment tracking, ML developer tools

  tagline:

    Better models by measuring

  tagline_width: 18em

  other_taglines:
    - Improve your models by measuring
    - Measure. Compare. Improve.
    - Measure, compare, and improve your models
    - Better Models Faster
    - The Right Model, Less Time
    - Systematic Machine Learning
    - Build Better Models Faster
    - Lightweight Experiment Tracking
    - The ML Engineering Platform
    - The ML Engineering Toolkit
    - Open source tools for ML engineering
    - Experiment Tracking for Machine Learning
    - Open Source Experiment Tracking for Machine Learning
    - Open Source ML Experiment Tracking

  subtext_width: 40em
  subtext:

  description:

    Guild AI is an open source experiment tracking toolkit. Use it to
    build better machine learning models faster.

  keywords:
    - Guild AI
    - Experiment Tracking
    - Machine Learning
    - Data Science
    - TensorFlow
    - TensorBoard
    - Reproducibility
    - PyTorch
    - Keras
    - Sacred
    - MLflow
    - Neptune
    - Weights and Biases
    - WandB
    - Comet
    - Polyaxon

  tagline_bullets:
    - text: Track Experiments
      icon: analytics-graph-white
    - text: Automate Pipelines
      icon: hierarchy-white
    - text: Tune Hyperparameter
      icon: seo-search-graph-gray
    - text: 100% Open Source
      icon: programming-flag-gray

  navbar:
    - name: Why Guild
      url: /why-guild/
    - name: FAQ
      url: /faq/
    - name: Services
      url: /services/
    - name: Docs
      url: https://my.guild.ai/docs
      ext: yes

  links:
    - name: github
      url: https://github.com/guildai/guildai
      title: Guild AI on GitHub
      icon_class: 'fab fa-github'
      header: yes
    - name: my.guild.ai
      url: https://my.guild.ai
      title: Guild AI Community
      icon_class: 'fab fa-discourse'
      header: yes
    - name: twitter
      url:  https://twitter.com/guildai
      title: Guild AI on Twitter
      icon_class: 'fab fa-twitter'
      header: yes
    - name: facebook
      url:  https://facebook.com/guildai
      title: Guild AI on Facebook
      icon_class: 'fab fa-facebook'
      header: yes

  # URL to edit Google fonts used in src/base.html:
  #
  # https://fonts.google.com/specimen/Roboto+Condensed?selection.family=Roboto+Condensed:wght@400;700|Roboto+Mono|Roboto+Slab|Roboto:wght@400;500;700&sidebar.open&query=roboto

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true

plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds:
  - serve

markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - extra
  - markdown_include.include:
      base_path: include
  - custom:MarkdownInHtml
  - custom:DefinitionId
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:PkgConfigList:
      src_path: ./packages
  - custom:DeflistToTable
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure

pages:
  - index.md
  - why-guild.md
  - services.md
  - faq.md
  - about.md
