site_name: Guild AI
docs_dir: pages

copyright: 2017-2018 TensorHub, Inc.

theme:
  name: null
  custom_dir: src

plugins:
  - search
  - nav_resolve

markdown_extensions:
  - plugins:ExternalLinks

pages:
  - index.md
  - install.md
  - docs:
      - docs/index.md
      - docs/packages.md
      - docs/models.md
      - docs/operations.md
      - docs/runs.md
      - Visualization:
          - docs/visual/guild-view.md
          - docs/visual/tensorboard.md
      - Commands:
          - docs/commands/check.md
          - docs/commands/compare.md
          - docs/commands/help.md
          - docs/commands/index.md
          - docs/commands/install.md
          - docs/commands/models.md
          - docs/commands/operations.md
          - docs/commands/package.md
          - docs/commands/packages.md
          - docs/commands/resources.md
          - docs/commands/run.md
          - docs/commands/runs.md
          - docs/commands/search.md
          - docs/commands/shell.md
          - docs/commands/sync.md
          - docs/commands/tensorboard.md
          - docs/commands/tensorflow.md
          - docs/commands/train.md
          - docs/commands/uninstall.md
          - docs/commands/view.md
      - Plugins:
          - docs/plugins/cloudml.md
          - docs/plugins/cpu.md
          - docs/plugins/disk.md
          - docs/plugins/keras.md
          - docs/plugins/gpu.md
          - docs/plugins/memory.md
      - Developer guides:
          - docs/developer/packaging.md
          - docs/developer/plugins.md
      - Reference:
          - docs/reference/plugin-api.md
          - docs/reference/model-file.md
          - docs/reference/package-file.md
      - Tutorials:
          - docs/tutorials/guild-from-scratch.md
      - docs/glossary.md
  - models:
      - models/index.md
      - models/keras.md
      - models/magenta.md
      - models/tensorflow.md
      - models/tfslim.md
  - support.md
