site_name: Guild AI
docs_dir: pages
copyright: 2018-2019 TensorHub, Inc.
strict: true
extra:
  rel_version: 0.6.5
  pre_version: 0.6.5

  tagline_width: 20em
  tagline:

    The easiest way to run, track, and compare
    machine learning experiments

  subtext_width: 30em
  subtext:

  links:
    - name: github
      url: https://github.com/guildai/guildai
      title: Guild AI on GitHub
      icon_class: 'fab fa-github'
      header: yes
    - name: slack
      url: https://join.slack.com/t/guildai/shared_invite/enQtNDgxNDg5ODk2MjI2LWQ5ODI3ZGE2YzljYWViNTA0NjFmNDg4NTI3ZjY2Mjk2YTkzZjAxZWM3M2EyNTcyZWU0YzgzM2IwMTI0ZjFhNTU
      title: Guild AI Slack Channel
      icon_class: 'fab fa-slack-hash'
      header: yes
    - name: twitter
      url:  https://twitter.com/guildai
      title: Guild AI on Twitter
      icon_class: 'fab fa-twitter'

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true
  static_templates:
    - version.html
plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds
  - serve
markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - extra
  - markdown_include.include:
      base_path: include
  - custom:MarkdownInHtml
  - custom:DefinitionId
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:PkgConfigList:
      src_path: ./packages
  - custom:DeflistToTable
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure
  - custom:NonbreakingHyphens
  - custom:Link:
      templates:
        # external links
        - text_pattern: '(.+?)\s?->'
          text: '{}'
          class: ext
          target: _blank
        # command
        - link_pattern: 'cmd:(.*)'
          class: cmd
          href: '/commands/{}-cmd'
          text: '{}'
        - link_pattern: 'pkg:(.*)'
          text: '{1}'
          href: /packages/{1}/
          class: pkg
        # term
        - link_pattern: 'term:(.*)'
          class: term
          text: '{0}'
          href: '{1}'
          arg_maps:
            - control-key: https://en.wikipedia.org/wiki/Control_key
              dependencies: /dependencies.md
              flag: /operations/#flags
              guild-env: /environments/
              guild-view: /tools/guild-view/
              guildfile: /guildfile/
              index: /reference/guild-home/#runs-index
              model-def: /models/#model-definition
              model: /models/
              operation-alias: /runs/#operation-aliases
              operation: /operations/
              package-file: /reference/package-file/
              package: /packages/
              remote: /remotes/
              resource-cache: /reference/guild-home/#resource-cache
              resource: /resources/
              run-dir: /runs/#run-directory
              run: /runs/
              tensorboard: /tools/tensorboard/
              test: /tests/
              user-config: /reference/user-config/
        # aliases
        - link_pattern: alias:install-guild
          href: /install/
          text: install Guild AI
        - link_pattern: alias:quick-start
          href: /start/
          text: Guild AI Quick Start
          class: doc
        - link_pattern: alias:guild-github
          href: https://github.com/guildai/guildai
          text: Guild AI GitHub project
          target: _blank
          class: ext
        - link_pattern: alias:guild-slack
          href: https://join.slack.com/t/guildai/shared_invite/enQtNDgxNDg5ODk2MjI2LWQ5ODI3ZGE2YzljYWViNTA0NjFmNDg4NTI3ZjY2Mjk2YTkzZjAxZWM3M2EyNTcyZWU0YzgzM2IwMTI0ZjFhNTU
          text: Guild AI Slack workspace
          class: ext
          target: _blank
        - link_pattern: alias:open-an-issue
          text: open an issue on GitHub
          class: ext
          target: _blank
          href: https://github.com/guildai/guildai/issues
        - link_pattern: alias:virtualenv-activate
          href: /tutorials/workflow-with-virtualenv/#using-a-virtual-environment
          text: activate your virtual environment
        - link_pattern: alias:running-commands
          href: /commands/#running-commands
          text: running commands
        - link_pattern: alias:separate-console
          href: /commands/#running-commands-in-a-separate-console
          text: separate console
        - link_pattern: alias:tut-env-setup
          href: /tutorials/#tutorial-virtual-environments
          text: Tutorial virtual environments
        - link_pattern: alias:tf-model-zoo
          href: https://github.com/tensorflow/models
          target: _blank
          class: ext
          text: TensorFlow model zoo
        - link_pattern: alias:packages
          href: /packages/
          text: Guild AI packages
        - link_pattern: alias:add-guild
          href: /guides/add-guild/
          text: Add Guild to a project
        - link_pattern: alias:pip
          text: pip
          href: https://pip.pypa.io/en/stable/
          target: _blank
          class: ext
        - link_pattern: alias:tmux
          text: tmux
          href: https://en.wikipedia.org/wiki/Tmux
          target: _blank
          class: ext
        - link_pattern: alias:create-object-detector
          text: Create an object detector
          href: /guides/create-object-detector/
        - link_pattern: alias:compare
          text: Guild Compare
          href: /tools/compare/

pages:
  - index.md
  - install.md
  - docs:
      - docs.md
      - start.md
      - cli.md
      - scripts.md
      - guildfiles.md
      - operations.md
      - tuning.md
      - workflow.md
      - models.md
      - environments.md
      - packages.md
      - remotes.md
      - How To:
          - howto/run-script.md
          - howto/tune-hyperparameters.md
          - howto/customize-script-inputs.md
          - howto/customize-script-outputs.md
          - howto/create-guildfile.md
          - howto/list-operations.md
          - howto/use-datasets-from-internet.md
          - howto/build-workflow.md
          - howto/debug-run-files.md
          - howto/debug-output-scalars.md
          - howto/customize-source-code-snapshots.md

      - Command Reference:
          - commands/index.md
          - commands/cat.md
          - commands/check.md
          - commands/compare.md
          - commands/diff.md
          - commands/download.md
          - commands/export.md
          - commands/help.md
          - commands/import.md
          - commands/index.md
          - commands/init.md
          - commands/install.md
          - commands/label.md
          - commands/ls.md
          - commands/models.md
          - commands/open.md
          - commands/operations.md
          - commands/package.md
          - commands/packages.md
          - commands/packages-delete.md
          - commands/packages-info.md
          - commands/packages-list.md
          - commands/pull.md
          - commands/push.md
          - commands/remote.md
          - commands/remote-start.md
          - commands/remote-status.md
          - commands/remote-stop.md
          - commands/remotes.md
          - commands/run.md
          - commands/runs.md
          - commands/runs-delete.md
          - commands/runs-diff.md
          - commands/runs-export.md
          - commands/runs-import.md
          - commands/runs-info.md
          - commands/runs-label.md
          - commands/runs-list.md
          - commands/runs-pull.md
          - commands/runs-purge.md
          - commands/runs-push.md
          - commands/runs-restore.md
          - commands/runs-stop.md
          - commands/search.md
          - commands/shell.md
          - commands/stop.md
          - commands/sync.md
          - commands/tensorboard.md
          - commands/tensorflow.md
          - commands/tensorflow-inspect.md
          - commands/uninstall.md
          - commands/view.md
          - commands/watch.md

      #- Reference:
  - cheatsheet.md
  - support.md
