site_name: Guild AI
docs_dir: pages
copyright: 2017-2018 TensorHub, Inc.
strict: true
extra:
  version: 0.5.0
  tagline:
    Task runner and package manager for TensorFlow.
  tagline_width: 16em
  subtext:
    Automate training, testing, and deployment. Capture runs as
    experiments. Install, share, and distribute your models.
  subtext_width: 26em
  links:
    - name: github
      url: https://github.com/guildai
    - name: twitter
      url:  https://twitter.com/guildai
theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true
  static_templates:
    - search.html
plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds
  - serve
markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - markdown_include.include:
      base_path: include
  - custom:DefinitionId
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:PkgConfigList:
      src_path: ./packages
  - custom:DeflistToTable
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure
  - custom:NonbreakingHyphens
  - custom:Link:
      templates:
        # external links
        - text_pattern: '(.+?)\s?->'
          text: '{}'
          class: ext
          target: _blank
        # command
        - link_pattern: 'cmd:(.*)'
          class: cmd
          href: '/docs/commands/{}-cmd'
          text: '{}'
        - link_pattern: 'pkg:(.*)'
          text: '{1}'
          href: /packages/{1}/
          class: pkg
        # term
        - link_pattern: 'term:(.*)'
          class: term
          text: '{0}'
          href: '{1}'
          arg_maps:
            - control-key: https://en.wikipedia.org/wiki/Control_key
              flag: /docs/operations/#flags
              guild-env: /docs/environments/
              guild-file: /docs/reference/guild-file/
              guild-view: /docs/visual/guild-view/
              index: /docs/reference/guild-home/#runs-index
              model-def: /docs/models/#model-definition
              model: /docs/models/
              operation-alias: /docs/runs/#operation-aliases
              operation: /docs/operations/
              package-file: /docs/reference/package-file/
              package: /docs/packages/
              remote: /docs/remotes/
              resource-cache: /docs/reference/guild-home/#resource-cache
              resource: /docs/resources/
              run-dir: /docs/runs/#run-directory
              run: /docs/runs/
              tensorboard: /docs/visual/tensorboard/
              test: /docs/tests/
              user-config: /docs/reference/user-config/
        # aliases
        - link_pattern: alias:install-guild
          href: /install/
          text: install Guild AI
        - link_pattern: alias:guild-github
          class: ext
          target: _blank
          href: https://github.com/guildai/guildai
          text: Guild AI GitHub project
        - link_pattern: alias:open-an-issue
          text: open an issue on GitHub
          class: ext
          target: _blank
          href: https://github.com/guildai/guildai/issues
        - link_pattern: alias:virtualenv-activate
          href: /docs/tutorials/workflow-with-virtualenv/#using-a-virtual-environment
          text: activate your virtual environment
        - link_pattern: alias:running-commands
          href: /docs/commands/#running-commands
          text: running commands
        - link_pattern: alias:separate-console
          href: /docs/commands/#running-commands-in-a-separate-console
          text: separate console
        - link_pattern: alias:tut-env-setup
          href: /docs/tutorials/#tutorial-virtual-environments
          text: Tutorial virtual environments
        - link_pattern: alias:tf-model-zoo
          href: https://github.com/tensorflow/models
          target: _blank
          class: ext
          text: TensorFlow model zoo
        - link_pattern: alias:packages
          href: /packages/
          text: Guild AI packages
        - link_pattern: alias:add-guild
          href: /docs/guides/add-guild/
          text: Add Guild to a project
        - link_pattern: alias:pip
          text: pip
          href: https://pip.pypa.io/en/stable/
          target: _blank
          class: ext
        - link_pattern: alias:tmux
          text: tmux
          href: https://en.wikipedia.org/wiki/Tmux
          target: _blank
          class: ext

pages:
  - index.md
  - install.md
  - docs:
      - docs/index.md
      - docs/intro.md
      - docs/models.md
      - docs/operations.md
      - docs/runs.md
      - docs/resources.md
      - docs/packages.md
      - docs/tests.md
      - docs/code-reuse.md
      - docs/environments.md
      - docs/remotes.md
      - Visualization:
          - docs/visual/guild-view.md
          - docs/visual/tensorboard.md
      - Commands:
          - docs/commands/index.md
          - docs/commands/cat-cmd.md
          - docs/commands/check-cmd.md
          - docs/commands/compare-cmd.md
          - docs/commands/diff-cmd.md
          - docs/commands/download-cmd.md
          - docs/commands/export-cmd.md
          - docs/commands/help-cmd.md
          - docs/commands/import-cmd.md
          - docs/commands/index-cmd.md
          - docs/commands/init-cmd.md
          - docs/commands/install-cmd.md
          - docs/commands/label-cmd.md
          - docs/commands/ls-cmd.md
          - docs/commands/models-cmd.md
          # - docs/commands/new-cmd.md
          - docs/commands/open-cmd.md
          - docs/commands/operations-cmd.md
          - docs/commands/package-cmd.md
          - docs/commands/packages-cmd.md
          - docs/commands/packages-delete-cmd.md
          - docs/commands/packages-info-cmd.md
          - docs/commands/packages-list-cmd.md
          - docs/commands/pull-cmd.md
          - docs/commands/push-cmd.md
          - docs/commands/remote-cmd.md
          - docs/commands/remote-start-cmd.md
          - docs/commands/remote-status-cmd.md
          - docs/commands/remote-stop-cmd.md
          - docs/commands/remotes-cmd.md
          - docs/commands/run-cmd.md
          - docs/commands/runs-cmd.md
          - docs/commands/runs-delete-cmd.md
          - docs/commands/runs-diff-cmd.md
          - docs/commands/runs-export-cmd.md
          - docs/commands/runs-import-cmd.md
          - docs/commands/runs-info-cmd.md
          - docs/commands/runs-label-cmd.md
          - docs/commands/runs-list-cmd.md
          - docs/commands/runs-pull-cmd.md
          - docs/commands/runs-purge-cmd.md
          - docs/commands/runs-push-cmd.md
          - docs/commands/runs-restore-cmd.md
          - docs/commands/runs-stop-cmd.md
          - docs/commands/search-cmd.md
          - docs/commands/shell-cmd.md
          - docs/commands/stop-cmd.md
          - docs/commands/sync-cmd.md
          - docs/commands/tensorboard-cmd.md
          - docs/commands/tensorflow-cmd.md
          - docs/commands/tensorflow-inspect-cmd.md
          - docs/commands/test-cmd.md
          - docs/commands/uninstall-cmd.md
          - docs/commands/view-cmd.md
          - docs/commands/watch-cmd.md
      # TODO - Plugins:
          # TODO - docs/plugins/index.md
          # TODO - docs/plugins/cloudml.md
          # TODO - docs/plugins/cpu.md
          # TODO - docs/plugins/disk.md
          # TODO - docs/plugins/keras.md
          # TODO - docs/plugins/gpu.md
          # TODO - docs/plugins/memory.md
      # TODO - Developer guides:
          # TODO - docs/developer/scripts.md
          # TODO - docs/developer/packaging.md
          # TODO - docs/developer/plugins.md
      - Reference:
          - docs/reference/guild-file.md
          - docs/reference/guild-home.md
          - docs/reference/user-config.md
          # TODO - docs/reference/plugin-api.md

      - Guides:
          - docs/guides/index.md
          # - delete failed runs
          # - reuse models
          # - create a tf lite file
          # - serve a trained model
          # - delete all runs
          # - archive runs
          # - restore runs from an archive
          # - train on EC2
          # - save runs on S3
          # - create a Guild file from scratch
          # - train on another server on my network
          # - work with resources
          # - list files generated by a run
          # - view files generated by a run
          # - compare runs
          # - share a project
          # - get information about an environment
          # - delete runs for a particular operation
          # - test models (include tricks -m, -o -1)
          # - diffing runs
          # - diff images using Beyond Compare
          #- docs/guides/convert-notebook.md
          - docs/guides/add-guild.md
          - docs/guides/create-image-classifier.md
          - docs/guides/create-object-detector.md
          - docs/guides/train-on-ec2.md
          - docs/guides/backup-to-s3.md
          - docs/guides/compare-runs.md
          - docs/guides/specify-run-gpus.md
          #- docs/guides/debug-operation.md
          #- docs/guides/create-tflite-file.md


      #- Tutorials:
      #    # - deep dive - understanding slim support
      #    - docs/tutorials/index.md
      #    - docs/tutorials/train-mnist.md
      #    # TODO - docs/tutorials/transfer-learning-with-imagenet.md
      #    - docs/tutorials/train-and-predict-with-cloudml.md
      #    # TODO - docs/tutorials/train-a-keras-model.md
      #    - docs/tutorials/develop-a-model-from-scratch.md
      #    # TODO - docs/tutorials/package-a-model.md
      #    # TODO - docs/tutorials/stylize-images-with-magenta.md
      #    - docs/tutorials/workflow-with-virtualenv.md
      #- troubleshooting.md
  - packages:
      - packages/index.md
      - Computer vision:
          - packages/object-detect.md
          - packages/object-detect-models.md
          - packages/slim.md
          - packages/slim-models.md
      - Art:
          - packages/keras-deep-dream.md
          - packages/magenta-image.md
          - packages/magenta-music.md
      - Example:
          - packages/hello.md
          - packages/keras-mnist.md
          - packages/mnist.md
  - support.md
  - faq.md
  - about.md
