site_name: Guild AI
docs_dir: pages

copyright: 2017-2018 TensorHub, Inc.

theme:
  name: null
  custom_dir: src

plugins:
  - search
  - nav_resolve

markdown_extensions:
  - toc:
      permalink: False

pages:
  - index.md
  - install.md
  - docs:
      - docs/index.md
      - docs/models.md
      - docs/operations.md
      - docs/packages.md
      - Tutorials:
          - docs/tutorials/index.md
      - docs/glossary.md
  - models:
      - models/index.md
      - models/keras.md
      - models/magenta.md
      - models/tensorflow.md
      - models/tfslim.md
  - support.md
