site_name: Guild AI
docs_dir: pages

copyright: 2017-2018 TensorHub, Inc.
extra:

  version: 0.5.0

  tagline:

    Automate TensorFlow tasks. Manage experiments. Reuse models.

  tagline_width: 18em

  subtext:

    Guild AI is a TensorFlow task runner and experiment tracker. It
    automates training, testing, deployment and use of your models.

  subtext_width: 32em

  links:
    - name: github
      url: https://github.com/guildai
    - name: twitter
      url:  https://twitter.com/guild_ai

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true
  static_templates:
    - search.html

plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds
  - serve

markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - custom:DefinitionId
  - custom:DeflistToTable
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure
  - custom:Link:
      templates:
        # external links
        - text_pattern: '(.+?)\s?->'
          text: '{}'
          class: ext
          target: _blank
        # command
        - link_pattern: 'cmd:(.*)'
          class: cmd
          href: '/docs/commands/{}-cmd'
          text: '{}'
        # term
        - link_pattern: 'term:(.*)'
          class: term
          text: '{0}'
          href: '{1}'
          arg_maps:
            - control-key: https://en.wikipedia.org/wiki/Control_key
              flag: /docs/operations/#flags
              guild-file: /docs/reference/guild-file/
              index: /docs/reference/guild-home/#runs-index
              model: /docs/models/
              model-def: /docs/models/#model-definition
              operation: /docs/operations/
              operation-alias: /docs/runs/#operation-aliases
              package-file: /docs/reference/package-file/
              package: /docs/packages/
              resource: /docs/resources/
              resource-cache: /docs/reference/guild-home/#resource-cache
              run-dir: /docs/runs/#run-directory
              run: /docs/runs/
        # aliases
        - link_pattern: alias:guild-github
          class: ext
          target: _blank
          href: https://github.com/guildai/guild
          text: Guild AI GitHub project
        - link_pattern: alias:open-an-issue
          text: open an issue on GitHub
          class: ext
          target: _blank
          href: https://github.com/guildai/guild/issues
        - link_pattern: alias:virtualenv-activate
          href: /docs/tutorials/workflow-with-virtualenv/#using-a-virtual-environment
          text: activate your virtual environment
        - link_pattern: alias:running-commands
          href: /docs/commands/#running-commands
          text: running commands
        - link_pattern: alias:separate-console
          href: /docs/commands/#running-commands-in-a-separate-console
          text: separate console
        - link_pattern: alias:tut-env-setup
          href: /docs/tutorials/#tutorial-virtual-environments
          text: Tutorial virtual environments
        - link_pattern: alias:tf-model-zoo
          href: https://github.com/tensorflow/models
          target: _blank
          class: ext
          text: TensorFlow model zoo
        - link_pattern: alias:guild-models
          href: /models/
          text: Guild AI models

pages:
  - index.md
  - install.md
  - docs:
      - docs/index.md
      - docs/intro.md
      - docs/models.md
      - docs/operations.md
      - docs/runs.md
      - docs/resources.md
      - docs/packages.md
      - Visualization:
          - docs/visual/guild-view.md
          - docs/visual/tensorboard.md
      - Commands:
          - docs/commands/index.md
          - docs/commands/check-cmd.md
          - docs/commands/compare-cmd.md
          - docs/commands/help-cmd.md
          - docs/commands/index-cmd.md
          - docs/commands/init-cmd.md
          - docs/commands/install-cmd.md
          - docs/commands/label-cmd.md
          - docs/commands/models-cmd.md
          - docs/commands/operations-cmd.md
          - docs/commands/package-cmd.md
          - docs/commands/packages-cmd.md
          - docs/commands/packages-delete-cmd.md
          - docs/commands/packages-info-cmd.md
          - docs/commands/packages-list-cmd.md
          - docs/commands/resources-cmd.md
          - docs/commands/run-cmd.md
          - docs/commands/runs-cmd.md
          - docs/commands/runs-delete-cmd.md
          - docs/commands/runs-info-cmd.md
          - docs/commands/runs-label-cmd.md
          - docs/commands/runs-list-cmd.md
          - docs/commands/runs-purge-cmd.md
          - docs/commands/runs-restore-cmd.md
          - docs/commands/runs-stop-cmd.md
          - docs/commands/search-cmd.md
          - docs/commands/shell-cmd.md
          - docs/commands/stop-cmd.md
          - docs/commands/sync-cmd.md
          - docs/commands/tensorboard-cmd.md
          - docs/commands/tensorflow-cmd.md
          - docs/commands/tensorflow-inspect-cmd.md
          - docs/commands/uninstall-cmd.md
          - docs/commands/view-cmd.md
      # TODO - Plugins:
          # TODO - docs/plugins/index.md
          # TODO - docs/plugins/cloudml.md
          # TODO - docs/plugins/cpu.md
          # TODO - docs/plugins/disk.md
          # TODO - docs/plugins/keras.md
          # TODO - docs/plugins/gpu.md
          # TODO - docs/plugins/memory.md
      # TODO - Developer guides:
          # TODO - docs/developer/scripts.md
          # TODO - docs/developer/packaging.md
          # TODO - docs/developer/plugins.md
      - Reference:
          - docs/reference/guild-file.md
          - docs/reference/guild-home.md
          # TODO - docs/reference/plugin-api.md
      - How to:

          # NOTE: How are these different from the other docs, which
          # already thorougly cover all topics? Can we skip the how to
          # section and just have topics for core concepts and
          # tutorials for extended step-by-step guides?
          #
          # The core concepts should each have an examples section
          # that can be used for copy/paste as much as possible for
          # any given desired task.

          # If we renamed Turorials to Guides, I think the guide-like
          # topics here could be moved there.

          - docs/howto/debug-an-operation.md
          - docs/howto/specify-run-gpus.md
          # - delete failed runs
          # - reuse models
          # - create a tf lite file
          # - serve a trained model
          # - delete all runs
          # - archive runs
          # - restore runs from an archive
          # - train on EC2
          # - save runs on S3
          # - create a Guild file from scratch
          # - train on another server on my network
          # - work with resources
          # - list files generated by a run
          # - view files generated by a run
          # - compare runs
          # - share a project
          # - get information about an environment
          # - delete runs for a particular operation
          # - test models (include tricks -m, -o -1)
          # - diffing runs
          # - diff images using Beyond Compare

      - Guides:
          - docs/guides/index.md
          - docs/guides/create-a-project.md
          - docs/guides/convert-jupyter.md
          - docs/guides/create-an-image-classifier.md
          - docs/guides/train-on-ec2.md
          - docs/guides/backup-to-s3.md
          - docs/guides/compare-runs.md
          - docs/guides/publish-to-pypi.md

      #- Tutorials:
      #    # - deep dive - understanding slim support
      #    - docs/tutorials/index.md
      #    - docs/tutorials/train-mnist.md
      #    # TODO - docs/tutorials/transfer-learning-with-imagenet.md
      #    - docs/tutorials/train-and-predict-with-cloudml.md
      #    # TODO - docs/tutorials/train-a-keras-model.md
      #    - docs/tutorials/develop-a-model-from-scratch.md
      #    # TODO - docs/tutorials/package-a-model.md
      #    # TODO - docs/tutorials/stylize-images-with-magenta.md
      #    - docs/tutorials/workflow-with-virtualenv.md
      #- troubleshooting.md
  - models:
      - models/index.md
      - Cloud ML:
          - models/cloudml/index.md
          - models/cloudml/census.md
          - models/cloudml/mnist.md
          - models/cloudml/datasets.md
      - Guild AI:
          - models/mnist.md
      - Keras:
          - models/keras/index.md
          - models/keras/deep-dream.md
          - models/keras/mnist.md
      - Magenta:
          - models/magenta/index.md
          - models/magenta/image.md
          - models/magenta/music.md
      - Official TensorFlow:
          - models/tensorflow/index.md
          - models/tensorflow/mnist.md
          - models/tensorflow/resnet.md
          - models/tensorflow/wide-deep.md
      - TF Slim:
          - models/slim/index.md
          - models/slim/inception.md
          - models/slim/resnet.md
          - models/slim/vgg.md
      - Wikipedia:
          - models/wikipedia/datasets.md
  - support.md
  - faq.md
  - about.md
