site_name: Guild AI
docs_dir: pages
copyright: 2018-2020 TensorHub, Inc.
strict: true
extra:
  version: 0.7.0
  contact_email: contact@guild.ai

  # IMPORTANT: sync pages/index.md title with tagline:
  tagline:

    The ML Engineering Toolkit

  tagline_width: 20em

  other_taglines:
    - The ML Engineering Platform
    - The ML Engineering Toolkit
    - Open source tools for ML engineering

  subtext_width: 40em
  subtext:

  tagline_bullets:
    - text: Experiment Tracking
      icon: folder-check-gray
    - text: Pipeline Automation
      icon: hierarchy-10-gray
    - text: Auto ML
      icon: seo-search-graph-gray
    - text: Open Source
      icon: programming-flag-gray

  navbar:
    - name: Why Guild
      url: /why-guild/
    - name: Docs
      url: https://my.guild.ai/docs
    - name: FAQ
      url: /faq/
    - name: Services
      url: /services/

  links:
    - name: my.guild.ai
      url: https://my.guild.ai
      title: Guild AI Community
      icon_class: 'fab fa-discourse'
      header: yes
    - name: github
      url: https://github.com/guildai/guildai
      title: Guild AI on GitHub
      icon_class: 'fab fa-github'
      header: yes
    - name: twitter
      url:  https://twitter.com/guildai
      title: Guild AI on Twitter
      icon_class: 'fab fa-twitter'
      header: yes

  clicky:

    # IMPORTANT: manually apply to src/base.html:
    prod: 100935573
    pre: 101236283

  # URL to edit Google fonts used in src/base.html:
  #
  # https://fonts.google.com/specimen/Roboto+Condensed?selection.family=Roboto+Condensed:wght@400;700|Roboto+Mono|Roboto+Slab|Roboto:wght@400;500;700&sidebar.open&query=roboto

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true

plugins:
  - search
  - nav_resolve
  # Modifies mkdocs server to avoid needless rebuilds:
  - serve

markdown_extensions:
  - admonition
  - footnotes
  - smarty
  - def_list
  - extra
  - markdown_include.include:
      base_path: include
  - custom:MarkdownInHtml
  - custom:DefinitionId
  - custom:CmdHelp:
      src_path: ./guild/guild/commands/
  - custom:PkgHelp:
      src_path: ./packages
  - custom:PkgConfigList:
      src_path: ./packages
  - custom:DeflistToTable
  - custom:MoveToc
  - custom:FixToc
  - custom:FencedCode
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure

pages:
  - index.md
  - why-guild.md
  - services.md
  - faq.md
  - docs.md
  - about.md
