site_name: Guild AI
docs_dir: pages

copyright: 2017-2018 TensorHub, Inc.

theme:
  name: null
  custom_dir: src

plugins:
  - search
  - nav_resolve

markdown_extensions:
  - toc:
      permalink: False

pages:
  - index.md
  - install.md
  - docs:
      - docs/index.md
      - docs/models.md
      - docs/operations.md
      - docs/packages.md
      - docs/glossary.md
  - pkgs:
      - pkgs/index.md
      - pkgs/keras.md
      - pkgs/magenta.md
      - pkgs/tensorflow.md
      - pkgs/tfslim.md
  - support.md
