site_name: Guild AI
docs_dir: pages

copyright: 2017-2018 TensorHub, Inc.
extra:
  tagline:
    Enabling the TensorFlow<sup>&reg;</sup> model ecosystem
  subtext:
    "Discover, install, and apply state-of-the-art deep learning
    models with Guild AI's comprehensive toolkit."
  links:
    - name: github
      url: https://github.com/guildai
    - name: twitter
      url:  https://twitter.com/guild_ai

theme:
  name: null
  custom_dir: src
  # The following want to be in src/mkdocs_theme.yml, but mkdocs only
  # reads that file when the theme is named/registered so we have to
  # include them here:
  include_search_page: false
  search_index_only: true
  static_templates:
    - search.html

plugins:
  - search
  - nav_resolve

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - smarty
  - toc
  - custom:FencedCode
  - custom:FixToc
  - custom:DefinitionId
  - custom:Classify:
      tags: [ul, ol, img]
  - custom:Categories
  - custom:Backtick
  - custom:Ref
  - custom:Figure
  - custom:Link:
      templates:
        # external links
        - text_pattern: '(.+?)\s?->'
          text: '{}'
          class: ext
          target: _blank
        # command
        - link_pattern: 'cmd:(.*)'
          class: cmd
          href: '/docs/commands/{}_cmd'
          text: '{}'
        # term
        - link_pattern: 'term:(.*)'
          class: term
          text: '{0}'
          href: '{1}'
          arg_maps:
            - control-key: https://en.wikipedia.org/wiki/Control_key
              flag: /docs/operations/#flags
              index: /docs/reference/guild-home/#runs-index
              model: /docs/models/
              operation: /docs/operations/
              package-file: /docs/reference/package-file/
              package: /docs/packages/
              resource: /docs/resources/
              run-dir: /docs/runs/#run-directory
              run: /docs/runs/
        # aliases
        - link_pattern: alias:guild-github
          class: ext
          target: _blank
          href: https://github.com/guildai/guild
          text: Guild AI GitHub project
        - link_pattern: alias:open-an-issue
          text: open an issue on GitHub
          class: ext
          target: _blank
          href: https://github.com/guildai/guild/issues
        - link_pattern: alias:virtualenv-activate
          href: /docs/tutorials/working-with-virtualenv/#using-a-virtual-environment
          text: activate your virtual environment
        - link_pattern: alias:running-commands
          href: /docs/commands/#running-commands
          text: running commands
        - link_pattern: alias:separate-console
          href: /docs/commands/#running-commands-in-a-separate-console
          text: separate console

pages:
  - index.md
  - install.md
  - docs:
      - docs/index.md
      - docs/overview.md
      - docs/models.md
      - docs/operations.md
      - docs/runs.md
      - Visualization:
          - docs/visual/index.md
          - docs/visual/guild-view.md
          - docs/visual/tensorboard.md
      - docs/packages.md
      - docs/resources.md
      - Commands:
          - docs/commands/index.md
          - docs/commands/check_cmd.md
          - docs/commands/compare_cmd.md
          - docs/commands/help_cmd.md
          - docs/commands/index_cmd.md
          - docs/commands/install_cmd.md
          - docs/commands/models_cmd.md
          - docs/commands/operations_cmd.md
          - docs/commands/package_cmd.md
          - docs/commands/packages_cmd.md
          - docs/commands/resources_cmd.md
          - docs/commands/run_cmd.md
          - docs/commands/runs_cmd.md
          - docs/commands/runs-list-cmd.md
          - docs/commands/search_cmd.md
          - docs/commands/shell_cmd.md
          - docs/commands/sync_cmd.md
          - docs/commands/tensorboard_cmd.md
          - docs/commands/tensorflow_cmd.md
          - docs/commands/train_cmd.md
          - docs/commands/uninstall_cmd.md
          - docs/commands/view_cmd.md
      - Plugins:
          - docs/plugins/index.md
          - docs/plugins/cloudml.md
          - docs/plugins/cpu.md
          - docs/plugins/disk.md
          - docs/plugins/keras.md
          - docs/plugins/gpu.md
          - docs/plugins/memory.md
      - Developer guides:
          - docs/developer/scripts.md
          - docs/developer/packaging.md
          - docs/developer/plugins.md
      - Reference:
          - docs/reference/plugin-api.md
          - docs/reference/model-file.md
          - docs/reference/package-file.md
          - docs/reference/guild-home.md
      - Tutorials:
          - docs/tutorials/index.md
          - docs/tutorials/train-your-first-model.md
          - docs/tutorials/transfer-learning-with-imagenet.md
          - docs/tutorials/guild-from-scratch.md
          - docs/tutorials/working-with-virtualenv.md
      - docs/glossary.md
  - models:
      - models/index.md
      - models/keras.md
      - models/magenta.md
      - models/tensorflow.md
      - models/tfslim.md
  - support.md
  - about.md
