[[redirects]]
  from = "https://www-pre.guild.ai/*"
  to = "https://guild.ai"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs"
  to = "https://my.guild.ai/docs"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/start"
  to = "https://my.guild.ai/start"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/support"
  to = "https://guild.ai/services"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/features"
  to = "https://guild.ai"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/optimizers"
  to = "https://my.guild.ai/reference/optimizers"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/remotes"
  to = "https://my.guild.ai/reference/remotes"
  status = 301
  force = true

[[redirects]]
  from = "https://my.guild.ai/terms/requirements-file"
  to = "https://bit.ly/guild-help-req-files"
  status = 301
  force = true
