[[redirects]]
  from = "https://guild.ai/docs"
  to = "https://my.guild.ai/docs"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/start"
  to = "https://my.guild.ai/start"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/support"
  to = "https://guild.ai/services"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/features"
  to = "https://guild.ai"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/optimizers"
  to = "https://my.guild.ai/reference/optimizers"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/remotes"
  to = "https://my.guild.ai/reference/remotes"
  status = 301
  force = true

[[redirects]]
  from = "https://my.guild.ai/terms/requirements-file"
  to = "https://bit.ly/guild-help-req-files"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/start/"
  to = "https://my.guild.ai/start"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/tests/"
  to = "https://my.guild.ai/docs"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/start/optimization/"
  to = "https://my.guild.ai/start/optimize"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/en/latest"
  to = "https://guild.ai/"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/install"
  to = "https://my.guild.ai/install"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/reference/guild-file/"
  to = "https://my.guild.ai/reference/guildfile"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/reference/guild-home/"
  to = "https://my.guild.ai/docs/environments"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/guides/compare/"
  to = "https://my.guild.ai/docs/compare"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/runs/"
  to = "https://my.guild.ai/docs/runs"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/start/reproducibility/"
  to = "https://my.guild.ai/start/guildfile"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/commands/tensorboard-cmd/"
  to = "https://my.guild.ai/commands/tensorboard"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/start/image-classifier/"
  to = "https://my.guild.ai/start"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/start/manage-runs/"
  to = "https://my.guild.ai/start/runs"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/commands/run-cmd/"
  to = "https://my.guild.ai/commands/run"
  status = 301
  force = true

[[redirects]]
  from = "https://guild.ai/docs/commands/runs-stop-cmd/"
  to = "https://my.guild.ai/commands/runs-stop"
  status = 301
  force = true
